version: 2
jobs:
  MacOS:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Install dependencies
          command: |
            brew tap vapor/homebrew-tap
            brew install cmysql
            brew install ctls
            brew install libressl
            brew install danger/tap/danger-swift 
            brew install swiftlint
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift package generate-xcodeproj --enable-code-coverage
            xcodebuild -scheme Sugar-Package -enableCodeCoverage YES test | xcpretty
      - run:
          name: Report coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Run Danger
          command: |
            danger-swift ci
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
  Linux:
    docker:
      - image: nodesvapor/vapor-ci:swift-4.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Copy Package File
          command: cp Package.swift res
      - run:
          name: Install dependencies
          command: |
            git clone https://github.com/danger/danger-swift.git
            cd danger-swift
            make install
            npm install -g danger
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Run Danger
          command: |
            danger-swift ci
      - run:
          name: Restoring Package File
          command: mv res Package.swift
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - MacOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop